### ISSUE TITLE
Missing credits

### ISSUE THREAD

**Issue by KrystianD** [dr-ni/bm2#1]
Hey @dr-ni,

I am really happy you made use of my work. That's great to see how the community grows with each one contribution.

However, as mentioned in the MIT license of my repo you initially forked from me, please mention the source of the repository that allowed you to decrypt the message from the device. I put a lot of work to reverse-engineer the protocol :)

**Comment by dr-ni** [comment]
Dear Krystian,

I'm currently working on all here - so sorry for not immediately including the credits - I wanted this already before.
If everything is ok now please close this issue.

Cheers Uwe

**Comment by KrystianD** [comment]
Thank you @dr-ni!
